# Generated by Django 3.1.5 on 2021-01-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('disc_number', models.PositiveIntegerField()),
                ('artist_name', models.CharField(max_length=100)),
                ('preview_URL', models.CharField(max_length=300)),
            ],
        ),
    ]
