# Generated by Django 3.1.5 on 2021-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.PositiveIntegerField(default=78000),
            preserve_default=False,
        ),
    ]
