# Generated by Django 3.1.5 on 2021-01-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_duration_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
