# Generated by Django 3.1.5 on 2021-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('releases', '0003_release_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='tags',
            field=models.ManyToManyField(related_name='pokemons', to='tags.Tag'),
        ),
    ]
