# Generated by Django 3.1.5 on 2021-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('releases', '0004_release_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pokemons', to='tags.Tag'),
        ),
    ]
