# Generated by Django 3.1.5 on 2021-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_release_favourited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(default='text', max_length=300),
            preserve_default=False,
        ),
    ]
