# Generated by Django 3.1.5 on 2021-01-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0008_release_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
