# Generated by Django 3.1.5 on 2021-01-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0009_auto_20210127_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
